baseURL = "https://github.com/Lavanderia-ponferrada/lacolada1"
languageCode = "es-ES"
  DefaultContentLanguage = "es"
title = "Lacolada Lavanderia Autoservicio Ponferrada"
themesDir = "themes"
theme = "hugo-serif-theme"
enableEmoji = true
enableRobotsTXT = false
canonifyURLs = true
enableGitInfo = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""
  author = "lacolada lavanderia automatica ponferrada"
  github = "https://github.com/Lavanderia-ponferrada"
  facebook = "https://www.facebook.com/Lacoladaponferrada"
  og_image = "/images/og.jpg"
  sitename = "Lacolada Lavanderia Autoservicio Ponferrada"
  twitter = "@Lacoladaponfe"

[languages]
  [languages.es]
    languageName = "Spanish"
    languageCode = "es"
    weight = 1

  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 2



  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true

  [params.logo]
    mobile = "images/logo1.svg"
    mobile_height = "36px"
    desktop = "images/logo1.svg"
    desktop_height = "36px"
    alt = "LaColada Lavanderia Autoservicio"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Comfortaa&display=swap'
    heading = "Comfortaa"
    base = "Comfortaa"

  [params.colors]
    primary = "#0099ff"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#ffffff"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_site = "@Lacoladaponfe"
    meta_twitter_creator = "@Lacoladaponfe"
    meta_og_image = "https://pbs.twimg.com/profile_images/1510375980963094528/1T9xqTI9_400x400.jpg"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = '<a class="lacolada" href="https://goo.gl/maps/gC5SBXKEicGkYx6q7">2022 ©Lacolada Lavanderia Autoservicio Ponferrada</a>'

[menu]
  # Main Menu

  [[menu.main]]
      name = "Lavadoras y secadoras"
      url = "/lavadoras-secadoras-automaticas/"
      weight = 1

  [[menu.main]]
      name = "Consejos de Limpieza"
      url = "/consejos/"
      weight = 2

  [[menu.main]]
      name = "Preguntas"
      url = "/preguntas-frecuentes-lavanderia/"
      weight = 3

  [[menu.main]]
      name = "Contacto"
      url = "/contacto/"
      weight = 4

  [[menu.main]]
      name = "Cómo llegar"
      url = "https://goo.gl/maps/gC5SBXKEicGkYx6q7"
      weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "LaColada"
    url = "/lacolada-lavanderia-ponferrada/"
      weight = 1

  [[menu.footer]]
    name = "Politica de privacidad"
    url = "/politica-de-privacidad/"
      weight = 2
